# This is hard-coded smelly code for demonstration purposes with golden-ration.py
# don't be like me, don't do this ;)
import termcolor

def fg():
    print(termcolor.colored('· ', 'red'),
          termcolor.colored('· ', 'blue'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'green'),
          termcolor.colored('· ', 'green'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'green'),
          termcolor.colored('· ', 'green'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'yellow'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))

    print(termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'cyan'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'),
          termcolor.colored('· ', 'magenta'))
